/*******************************************************************************
* Copyright © 2024-2025 Light Zhang <mapaware@hotmail.com>, MapAware, Inc.     *
* ALL RIGHTS RESERVED.                                                         *
*                                                                              *
* PERMISSION IS HEREBY GRANTED, FREE OF CHARGE, TO ANY PERSON OR ORGANIZATION  *
* OBTAINING A COPY OF THE SOFTWARE COVERED BY THIS LICENSE TO USE, REPRODUCE,  *
* DISPLAY, DISTRIBUTE, EXECUTE, AND TRANSMIT THE SOFTWARE, AND TO PREPARE      *
* DERIVATIVE WORKS OF THE SOFTWARE, AND TO PERMIT THIRD - PARTIES TO WHOM THE  *
* SOFTWARE IS FURNISHED TO DO SO, ALL SUBJECT TO THE FOLLOWING :               *
*                                                                              *
* THE COPYRIGHT NOTICES IN THE SOFTWARE AND THIS ENTIRE STATEMENT, INCLUDING   *
* THE ABOVE LICENSE GRANT, THIS RESTRICTION AND THE FOLLOWING DISCLAIMER, MUST *
* BE INCLUDED IN ALL COPIES OF THE SOFTWARE, IN WHOLE OR IN PART, AND ALL      *
* DERIVATIVE WORKS OF THE SOFTWARE, UNLESS SUCH COPIES OR DERIVATIVE WORKS ARE *
* SOLELY IN THE FORM OF MACHINE - EXECUTABLE OBJECT CODE GENERATED BY A SOURCE *
* LANGUAGE PROCESSOR.                                                          *
*                                                                              *
* THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR   *
* IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,     *
* FITNESS FOR A PARTICULAR PURPOSE, TITLE AND NON - INFRINGEMENT.IN NO EVENT   *
* SHALL THE COPYRIGHT HOLDERS OR ANYONE DISTRIBUTING THE SOFTWARE BE LIABLE    *
* FOR ANY DAMAGES OR OTHER LIABILITY, WHETHER IN CONTRACT, TORT OR OTHERWISE,  *
* ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER  *
* DEALINGS IN THE SOFTWARE.                                                    *
*******************************************************************************/
/*
** @file cgtypes.h
** @brief C Gemoetry Types Definitions
**
** @author mapaware@hotmail.com
** @copyright © 2024-2030 mapaware.top All Rights Reserved.
** @version 0.1.3
**
** @since 2024-10-16 12:45:30
** @date 2024-10-16 22:09:07
**
** @note
*/
#ifndef GEOMTYPE_H__
#define GEOMTYPE_H__

#if defined(__cplusplus)
extern "C"
{
#endif

#include <stdint.h>
#include <math.h>
#include <float.h>
#include <memory.h>


typedef struct
{
    double X;
    double Y;
} CGPoint2D;


typedef struct
{
    int64_t X;
    int64_t Y;
} CGPoint2L;


typedef struct
{
    double W;   // Width
    double H;   // Height
} CGSize2D;


typedef struct
{
    union {
        struct {
            double Xmin;
            double Ymin;
        };
        CGPoint2D minPt;
    };

    union {
        struct {
            double Xmax;
            double Ymax;
        };
        CGPoint2D maxPt;
    };
} CGBox2D;


typedef struct
{
    union {
        struct {
            int64_t Xmin;
            int64_t Ymin;
        };
        CGPoint2L minPt;
    };

    union {
        struct {
            int64_t Xmax;
            int64_t Ymax;
        };
        CGPoint2L maxPt;
    };
} CGBox2L;


#define CG_ABS(v)       ((v) < 0? -(v):(v))
#define CG_MIN(a, b)    ((a) < (b) ? (a) : (b))
#define CG_MAX(a, b)    ((a) > (b) ? (a) : (b))

#define CGPointNotEqual(X1, Y1, X2, Y2, precision)   (X1-X2>precision || Y1-Y2>precision || X2-X1>precision || Y2-Y1>precision)


#define CGBoxGetDX(box)   (box.Xmax - box.Xmin)
#define CGBoxGetDY(box)   (box.Ymax - box.Ymin)

#define CGBoxIsOverlap(a, b)   ((a).Xmin<(b).Xmax && (a).Ymin<(b).Ymax && (b).Xmin<(a).Xmax && (b).Ymin<(a).Ymax)

#define CGBoxInflate(box, d)   do { box.Xmin -= d; box.Ymin -= d; box.Xmax += d; box.Ymax += d; } while(0)

#ifdef __cplusplus
}
#endif
#endif /* GEOMTYPE_H__ */
