# @file      Makefile
#   Makefile both for mingw on windows
#
# @copyright Copyright(c) 2024, mapaware.top
# @since 2024-10-29 13:01:18
# @date      2024-10-29 16:29:40
########################################################################

.PHONY: all clean

all:
	@echo "TODO: $(CURDIR)"

clean:
	@/usr/bin/find . -type f -name '*.o' | xargs -I {} sh -c "rm -f {}"
	@echo "[clean] done: $(CURDIR)"